<a href="https://colab.research.google.com/github/AIML-Dept/RithikaRajavel_1GA23AI041/blob/main/WEEK_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial 3: Single-Qubit Quantum Gates

## Objective

In this tutorial, we study and implement the Pauli-X, Pauli-Y,
Pauli-Z and Hadamard gates.

We will also examine their matrix representations, observe how
they transform a qubit state, and build a simple circuit using
multiple single-qubit gates.


## Learning Objectives

- Implement Pauli-X, Pauli-Y, Pauli-Z and Hadamard gates.
- Understand the matrix representation of quantum gates.
- Observe how gates transform the |0⟩ and |1⟩ states.
- Combine multiple gates in a quantum circuit.
- Interpret the final quantum state.

In [ ]:
!pip install qiskit
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
import numpy as np

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 78.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 65.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 4.1 MB/s eta 0:00:00


## 1. Pauli-X Gate

The Pauli-X gate acts like a quantum NOT gate.

It changes:

|0⟩ → |1⟩

and

|1⟩ → |0⟩

Its matrix representation is:

X = [[0, 1],
     [1, 0]]

In [ ]:
qc_x = QuantumCircuit(1)

qc_x.x(0)

print(qc_x)

state_x = Statevector.from_instruction(qc_x)

print("State after X gate:")
print(state_x)

   ┌───┐
q: ┤ X ├
   └───┘
State after X gate:
Statevector([0.+0.j, 1.+0.j],
            dims=(2,))


## 2. Pauli-Y Gate

The Pauli-Y gate changes the qubit state while also introducing
a phase factor.

Its matrix representation is:

Y = [[0, -i],
     [i,  0]]


In [ ]:
qc_y = QuantumCircuit(1)

qc_y.y(0)

print(qc_y)

state_y = Statevector.from_instruction(qc_y)

print("State after Y gate:")
print(state_y)

   ┌───┐
q: ┤ Y ├
   └───┘
State after Y gate:
Statevector([0.+0.j, 0.+1.j],
            dims=(2,))


## 3. Pauli-Z Gate

The Pauli-Z gate changes the phase of the |1⟩ state while leaving
the |0⟩ state unchanged.

Its matrix representation is:

Z = [[1,  0],
     [0, -1]]

In [ ]:
qc_z = QuantumCircuit(1)

qc_z.z(0)

print(qc_z)

state_z = Statevector.from_instruction(qc_z)

print("State after Z gate:")
print(state_z)

   ┌───┐
q: ┤ Z ├
   └───┘
State after Z gate:
Statevector([1.+0.j, 0.+0.j],
            dims=(2,))


## 4. Hadamard Gate

The Hadamard gate creates an equal superposition of |0⟩ and |1⟩.

For an initial |0⟩ state:

H|0⟩ = (|0⟩ + |1⟩) / √2

Its matrix representation is:

H = 1/√2 [[1,  1],
           [1, -1]]

In [ ]:
qc_h = QuantumCircuit(1)

qc_h.h(0)

print(qc_h)

state_h = Statevector.from_instruction(qc_h)

print("State after H gate:")
print(state_h)

   ┌───┐
q: ┤ H ├
   └───┘
State after H gate:
Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))


## 5. Gate Matrix Representation

The following matrices show the mathematical representation
of the four single-qubit gates studied in this tutorial.

In [ ]:
X = np.array([
    [0, 1],
    [1, 0]
])

Y = np.array([
    [0, -1j],
    [1j, 0]
])

Z = np.array([
    [1, 0],
    [0, -1]
])

H = (1 / np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

print("Pauli-X:\n", X)
print("\nPauli-Y:\n", Y)
print("\nPauli-Z:\n", Z)
print("\nHadamard:\n", H)

Pauli-X:
 [[0 1]
 [1 0]]

Pauli-Y:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

Pauli-Z:
 [[ 1  0]
 [ 0 -1]]

Hadamard:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


## 6. Combining Multiple Gates

Quantum gates can be applied sequentially to transform a qubit.

In this circuit, we first apply a Hadamard gate and then a
Pauli-Z gate.

The final state will be examined using the statevector.

In [ ]:
qc_combined = QuantumCircuit(1)

qc_combined.h(0)
qc_combined.z(0)

print(qc_combined)

final_state = Statevector.from_instruction(qc_combined)

print("Final Statevector:")
print(final_state)

   ┌───┐┌───┐
q: ┤ H ├┤ Z ├
   └───┘└───┘
Final Statevector:
Statevector([ 0.70710678+0.j, -0.70710678+0.j],
            dims=(2,))


## Conclusion

The Pauli-X, Pauli-Y and Pauli-Z gates perform different
transformations on a qubit, while the Hadamard gate creates
superposition.

Quantum gates can also be combined sequentially to produce
different target states.

The statevector allows us to observe and interpret the effect
of these operations mathematically.